package mz.co.moovi.mpesalib.api

/**
 * Data class that represents the response from the Customer-to-Business (C2B) Mpesa Transaction
 * @output_ConversationID: This gets generated by the Mobile Money platform. This is used to query transactions on the Mobile Money Platform.
 * @output_ResponseCode: This gets generated by the iPG platform to indicate the status of the transaction
 * @output_TransactionID: This gets generated by the Mobile Money platform. This is used to query transactions on the Mobile Money Platform.
 * @output_ResponseDesc: This gets generated by the iPG platform to indicate the status of the transaction
 * @output_ThirdPartyReference: This is the reference of the third party system. When there are queries about transactions, this will usually be used to track a transaction.
 */
data class PaymentResponse(
    val output_ConversationID: String,
    val output_ResponseCode: String,
    val output_TransactionID: String,
    val output_ResponseDesc: String,
	val output_ThirdPartyReference: String
)