package mz.co.moovi.mpesalib.api.c2b

import com.squareup.moshi.Json

/**
 * Data class that represents the response from the Customer-to-Business (C2B) Mpesa Transaction
 * @output_ConversationID: This gets generated by the Mobile Money platform. This is used to query transactions on the Mobile Money Platform.
 * @output_ResponseCode: This gets generated by the iPG platform to indicate the status of the transaction
 * @output_TransactionID: This gets generated by the Mobile Money platform. This is used to query transactions on the Mobile Money Platform.
 * @output_ResponseDesc: This gets generated by the iPG platform to indicate the status of the transaction
 */
data class C2BPaymentResponse(
    @Json(name = "output_ResponseCode") val responseCode: String,
    @Json(name = "output_ResponseDesc") val responseDesc: String,
    @Json(name = "output_TransactionID") val transactionId: String?,
    @Json(name = "output_ConversationID") val conversationId: String?
)